# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

matrix:
    include:
      - jdk: openjdk8
      - jdk: openjdk9
      - jdk: openjdk10
      - jdk: openjdk11
      - jdk: oraclejdk8
      - jdk: oraclejdk10
    allow_failures:
      - jdk: openjdk-ea
      - jdk: oraclejdk-ea

#Cache downloaded Maven artifacts between builds
cache:
  directories:
      - "${HOME}/.m2"
  
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN
