%YAML 1.1

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

matrix:
    include:
      - jdk:
        - openjdk8
        - openjdk9
        - openjdk10
        - openjdk11
        - oraclejdk8
        - oraclejdk10
    allow_failure:
      - jdk:
        - openjdk-ea
        - oraclejdk-ea
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  
#Cache downloaded Maven artifacts between builds
cache:
  directories:
      - "${HOME}/.m2"
  
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN
