# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
#  - oraclejdk10
#  - oraclejdk11

#Cache downloaded Maven artifacts between builds
cache:
  directories:
      - "${HOME}/.m2"
  
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN
